### PR TITLE
fix: prevent false positive secret replacement

### LINKED ISSUE #1558: False positives with hide-sensitive [secure] output
## Current behavior

One example: the [toReplace function](https://github.com/semantic-release/semantic-release/blob/0ef52e7a5f4f4c2bc3daecf7d71eeb1323491374/lib/hide-sensitive.js#L6) will match on the env var [`GOPRIVATE`](https://golang.org/cmd/go/#hdr-Module_configuration_for_non_public_modules) when using semantic-release on Go projects with that setting configured.  `GOPRIVATE` will typically have the same hostname as `repositoryUrl` in internal corporate networks.

If `GOPRIVATE=host.com` and `repositoryUrl=https://host.com/owner/repo.git` for example, then this breaks the links generated in release notes and changelog:

```
# [1.1.0](https://[secure]/owner/repo/compare/v1.0.0...v1.1.0) (2020-05-19)

### Features

* my feature ([d6c2e99a](https://[secure]/owner/repo/commit/d6c2e99aa27324878e7068a2c84229738b483794))
f502ba0a

```

## Expected behavior

In this scenario, `host.com` should not be replaced with `[secure]`:

```
# [1.1.0](https://host.com/owner/repo/compare/v1.0.0...v1.1.0) (2020-05-19)

### Features

* my feature ([d6c2e99a](https://host.com/owner/repo/commit/d6c2e99aa27324878e7068a2c84229738b483794))
f502ba0a

```

## Environment

- **semantic-release** version: 17.0.7
- CI environment: hosted Gitlab
- Plugins used: commit-analyzer,release-notes-generator,exec,changelog,git,gitlab
- **semantic-release** configuration: 
- CI logs:

### PR DESCRIPTION
**Pull request by nickshine**
Resolve #1558

### CODE REVIEW

File: lib/hide-sensitive.js [hunk 1]
```diff
@@ -3,7 +3,8 @@ const {SECRET_REPLACEMENT, SECRET_MIN_SIZE} = require('./definitions/constants')
 
 module.exports = (env) => {
   const toReplace = Object.keys(env).filter(
-    (envVar) => /token|password|credential|secret|private/i.test(envVar) && size(env[envVar].trim()) >= SECRET_MIN_SIZE
+    (envVar) =>
+      /token|password|credential|secret|(?<!^go)private/i.test(envVar) && size(env[envVar].trim()) >= SECRET_MIN_SIZE
```
Comment (gr2m) [inline lib/hide-sensitive.js:7]: I'm not 100% sure about adding a workaround for one specific environment variable, but I have no better idea either. What I would do however is to make the code more readable and to comment the workaround. I'd suggest to do the following

```suggestion
    (envVar) => {
      // https://github.com/semantic-release/semantic-release/issues/1558
      if (envVar === 'GOPRIVATE') {
        return false
      }
      
      return /token|password|credential|secret|private/i.test(envVar) && size(env[envVar].trim()) >= SECRET_MIN_SIZE
    }
```

Comment (nickshine) [reply lib/hide-sensitive.js:7]: Sounds good @gr2m.  I thought about adding a debug line to print out matched env vars... that sure would have helped me figure this one out a lot sooner.
