### PR TITLE
fix: do not transform repositoryUrl if it allow to push

### LINKED ISSUE #667: git repository url forcefully converted to https
# Bug report

## Current behavior

I'm trying to release a project hosted on gitlbab. 
I'm using ssh agent for the git operations and I'm providing a GL_TOKEN env variable for the gitlab release.
the repository.url is in the package.json is in the form `git@hostname:group/project.git`

Unluckily semantic-release always convert the repo url to `https://hostname/group/project.git` unless it's explicitly using the `http` protocol (https://github.com/semantic-release/semantic-release/blob/caribou/lib/get-git-auth-url.js#L23) and tries to use the GL_TOKEN for authentication. 

As my gitlab is using http protocol the `https://hostname/group/project.git` endpoint is invalid and the release fails at the `verifyAuth` step (https://github.com/semantic-release/semantic-release/blob/caribou/lib/git.js#L89) as that will call `git  push --dry-run https://hostname/group/project.git HEAD:${branch}`

I don't see the reason why the semantic-release should forcefully use an http/https endpoint when git protocol (with ssh credential) is available

If i change the repository.url to `http://hostname/group/project.git` then everything works correctly (but ssh agent is not used)

## Expected behavior

The git operations should be performed suing the git url (hence using the ssh key) while still be able to call the gitlab api using the provided GL_TOKEN

## Environment

- **semantic-release** version: 13.4
- CI environment: jenkins but can reproduce locally
- Plugins used: npm, git, gitlab
- **semantic-release** configuration: 
```
"release": {
    "branch": "master",
    "debug": true,
    "verifyConditions": [
      "@semantic-release/git",
      "@semantic-release/gitlab"
    ],
    "publish": [
      {
        "path": "@semantic-release/npm",
        "npmPublish": false,
        "tarballDir": "artifacts"
      },
      "@semantic-release/git",
      "@semantic-release/gitlab"
    ],
    "success": [],
    "fail": [],
    "gitlabUrl": "http://someip"
  },
```

### PR DESCRIPTION
**Pull request by pvdlg**
Fix #667

Use the unmodified configured repositoryUrl (without adding the credentials) if it works, otherwise do as of now and convert the URL to `http`/`https` and add the credentials.

This allow users to push tags and commits via ssh while still using the GitHub/GitLab API.

### CODE REVIEW

File: lib/get-config.js [hunk 1]
```diff
@@ -51,7 +51,10 @@ module.exports = async (opts, logger) => {
     ...pickBy(options, option => !isUndefined(option) && !isNull(option)),
   };
 
-  options.repositoryUrl = options.repositoryUrl ? getGitAuthUrl(options.repositoryUrl) : options.repositoryUrl;
+  console.log(options.repositoryUrl, options.branch);
```
Comment (brokenmass) [inline lib/get-config.js]: do you want this `console.log` ? shouldn't be a `debug()` ?

Comment (pvdlg) [reply lib/get-config.js]: Oops that was for dev debugging and I forgot to remove it. Good catch!

**Comment by brokenmass** [comment]
I tested in my environment and now it's working correctly so all good for me, you can merge.

**Comment by pvdlg** [comment]
Thanks !
