### PR TITLE
 fix: fetch all tags even if the repo is not shallow

### LINKED ISSUE #841: Tags are not fetched if repo is not shallow
## Current behavior

Buildkite uses non-shallow repositories and fetches the specific commit for the build with `git fetch -v origin <commithash>`. Tags are therefor not fetched. The command `git fetch --unshallow --tags` therefor fails with
```
fatal: --unshallow on a complete repository does not make sense
```
and does not fetch the tags, meaning no last release is found.

In addition the error is not printed (#840 should fix this).

## Expected behavior

It should fetch the tags

## Environment

- **semantic-release** version: 15.6.0 
- CI environment: Buildkite
- Plugins used: default 
- **semantic-release** configuration: default 
- CI logs: 
```
~~~ Preparing working directory
[90m$[0m cd /buildkite/builds/buildkite-agent-54c7fc7b54-tljqj/sourcegraph/REDACTED
[90m# Host "github.com" already in list of known hosts at "/root/.ssh/known_hosts"[0m
[90m$[0m git remote set-url origin git@github.com:sourcegraph/REDACTED.git
[90m$[0m git clean -fxdq
[90m$[0m git fetch -v origin 8c4dbb7998f4bdd15ba9678a416544cb2887815d
From github.com:sourcegraph/REDACTED

 * branch            8c4dbb7998f4bdd15ba9678a416544cb2887815d -> FETCH_HEAD

[90m$[0m git checkout -f 8c4dbb7998f4bdd15ba9678a416544cb2887815d
HEAD is now at 8c4dbb7 ci: add semantic-release

[90m# Cleaning again to catch any post-checkout changes[0m
[90m$[0m git clean -fxdq
[90m# Checking to see if Git data needs to be sent to Buildkite[0m
[90m$[0m buildkite-agent meta-data exists buildkite:git:commit
~~~ Running commands
[90m$[0m npm ci
npm run build
npm run semantic-release

[Semantic release]: Running semantic-release version 15.6.0

[Semantic release]: Load plugin "verifyConditions" from @semantic-release/npm

[Semantic release]: Load plugin "verifyConditions" from @semantic-release/github

[Semantic release]: Load plugin "analyzeCommits" from @semantic-release/commit-analyzer

[Semantic release]: Load plugin "generateNotes" from @semantic-release/release-notes-generator

[Semantic release]: Load plugin "prepare" from @semantic-release/npm

[Semantic release]: Load plugin "publish" from @semantic-release/npm

[Semantic release]: Load plugin "publish" from @semantic-release/github

[Semantic release]: Load plugin "success" from @semantic-release/github

[Semantic release]: Load plugin "fail" from @semantic-release/github

[Semantic release]: Run automated release from branch master

[Semantic release]: Call plugin verify-conditions

[Semantic release]: Verify authentication for registry https://registry.npmjs.org/

[Semantic release]: Verify GitHub authentication

[Semantic release]: No git tag version found

[Semantic release]: No previous release found, retrieving all commits

[Semantic release]: Found 20 commits since last release

[Semantic release]: Call plugin analyze-commits

[Semantic release]: Analyzing commit: ci: add semantic-release

[Semantic release]: The commit should not trigger a release

[...]

[Semantic release]: Analysis of 20 commits complete: patch release

[Semantic release]: There is no previous release, the next release version is 1.0.0

[Semantic release]: Call plugin verify-release

[Semantic release]: Call plugin generateNotes

[Semantic release]: Call plugin prepare

[Semantic release]: Wrote version 1.0.0 to package.json

[Semantic release]: Wrote version 1.0.0 to package-lock.json

[Semantic release]: Create tag v1.0.0

[Semantic release]: Call plugin publish

[Semantic release]: Publishing version 1.0.0 to npm registry

+ @sourcegraph/REDACTED@1.0.0[Semantic release]: Published GitHub release: https://github.com/sourcegraph/REDACTED/releases/tag/v1.0.0

[Semantic release]: Published release: 1.0.0
```

### PR DESCRIPTION
**Pull request by pvdlg**
Fix #841

### CODE REVIEW

File: lib/git.js [hunk 1]
```diff
@@ -49,15 +49,15 @@ async function isRefInHistory(ref) {
...
  *
  * @param {String} repositoryUrl The remote repository URL.
  */
-async function unshallow(repositoryUrl) {
+async function fetch(repositoryUrl) {
   try {
     await execa('git', ['fetch', '--unshallow', '--tags', repositoryUrl]);
   } catch (err) {
-    debug(err);
+    await execa('git', ['fetch', '--tags', repositoryUrl]);
```
Comment (felixfbecker) [inline lib/git.js]: if this command fails too, could you log the output?

Comment (pvdlg) [reply lib/git.js]: If this command fail the error will be propagated and logged upstream.
