### PR TITLE
fix: fix the `--no-ci` arg parsing

### LINKED ISSUE #616: The `--no-ci` option is ignored
## Current behavior

When calling `semantic-release --no-ci`, the parameter is ignored.
`commander` set `options.noCi` as `undefined`, instead the `options.ci` is set to `true`.

In addition the `noCi` options from the config files is loaded only after checking `options.noCi`. So `noCi` from a config file is effectively ignored.

## Expected behavior

`semantic-release --no-ci` should be parsed properly.

### PR DESCRIPTION
**Pull request by pvdlg**
The `noCi` is no properly set based on the `--no-ci` CLI arg and it is overwritten by the `noCi` option.

Fix #616

### CODE REVIEW

File: cli.js [hunk 1]
```diff
@@ -48,8 +48,11 @@ module.exports = async () => {
       program.outputHelp();
       process.exitCode = 1;
     } else {
+      const opts = program.opts();
+      // Set the `noCi` options as commander.js sets the `ci` options instead (becasue args strats with `--no`)
```
Comment (travi) [inline cli.js]: typo: "strats" => "starts"

Comment (pvdlg) [reply cli.js]: Thanks!
